### PR TITLE
Feature/profile

### PR DESCRIPTION
**Pull request by andre-merzky**
This PR adds basic profiling capabilities on the repex layer.  It should be merged after PR #37 has been accepts which will minimize the diff.

### CODE REVIEW

**Comment by andre-merzky** [comment]
Argh, and again on the wrong repo...  This seems to be set as default target for repex pull requests, and I did not find a way to change that.  Is this clone of the repository still used?

Anyway, apologies for the noise...

**Comment by SrinivasMushnoori** [comment]
No worries Andre. No this repo is deprecated. The RCT one is the one that should be used...

**Comment by andre-merzky** [comment]
We may want to remove it then, maybe?

**Comment by SrinivasMushnoori** [comment]
Well the reason we keep it around is because my advisor wanted it so. Fundamentally she wanted a copy of the code online at all times (the code I wrote for the fellowship). Let me see if I can have her clone the repo so she has it. In the interim, will renaming the repository help with the PR conflict?

**Comment by SrinivasMushnoori** [comment]
@andre-merzky Here's an alternative: we can merge from the RCT RepEx repo into mine, and then merge back so both repos are basically current. Would that work?

**Comment by andre-merzky** [comment]
I don't mind if you want to keep this repo and merge from the RCT one, no worries.  I'll be a bit more careful on the PR creation then :-)  I don't think there are commits in this repo which need merging back though.

**Pull request closed without merging**
